set_timewindows:
  description: "Set timewindows for Froeling Connect facilities."
  target:
    entity:
      integration: froeling_connect
      domain: sensor
  fields:
    timewindows:
      description: "A list of timewindows to set for the facility. Take this from the timewindow sensor attributes."
      required: true
      selector:
        object: